language: cpp

os:
  - linux
  - osx

# don't re-build for tags so that [publish binary] is not re-run
# https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^v[0-9]/

env:
  matrix:
    - NODE_VERSION="0.12"
    - NODE_VERSION="4"
    - NODE_VERSION="5"
    - NODE_VERSION="6"
    - NODE_VERSION="7"
    - NODE_VERSION="iojs"
  global:
    - secure: GM28mePDOytl0OQkWU8ayDmWbk4yn8YNiFD3zUJV/FJq9RbIZl5UhUgZ75TWPILusficM1jCPsQZRLZrXYHyA2mquH3lxM7T83O7YwYtGYS00/FJFZEsEnAln8tTBCkzvhK0++wypGJg05liqy3K3RIp75QIKSUGoETfaurvwvm2fbxhRaw763TJi6aktjcv6BwzlpsAmWDFw7G9lGvSAgwF2v6f8E8F1P3vLzCmxXX/u0iQyE0LXFgqrizmALwS+bFQJDNl+jETZpMPLHj8LWZC7vmOORRop5mVBDBuPHuFIBcKqVVnan+rZyPEd6QSwojNY+ya+ymEWp5tL/xfuOf5ql3Mw2mXEghhfhQHYQATACUcrXHBsEfCEXsXsVDB9Zg9C6llbWB8xfLIVuwNK1NnOcnZrZJHxj4X4mEEeUdALtYe70xdK3HpIhFrz0CvWtYjl2OhA5tkH4OZOxAUSHtDb/KdXEzw4p80Jl1xxSsb2GhGe3lkTW5SqI34+Sy6CftVRBb86NgpmU5JaR041m5W5h2RhJxiLJtJHBwWL+DeMQ7gObo1vDJ/LvlFprLTAJ+q96SIu6P3CdCsS2b1a381ImXZBVL75qn0IPKMqJzMxjxifXFndWnhp2X7YTOc6nrfOqe24DlJLKEKR0psIndwIALXVDvg36R9s0pNymc

matrix:
  fast_finish: true

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - export CXX=g++
  - export CC=gcc
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8; fi
  - rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

install:
  - npm install --build-from-source

script:
  - npm run lint
  - npm run test-cov

after_success:
  - npm run coveralls
  - COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
  - if [[ ${COMMIT_MESSAGE} =~ "[publish]" ]]; then $(npm bin)/node-pre-gyp package && $(npm bin)/node-pre-gyp-github publish; fi;
